apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ .Values.apps.path }}
    repoURL: {{ .Values.apps.url }}
    targetRevision: {{ .Values.apps.branch }}
    directory:
      recurse: true
      exclude: '*.json'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
