apiVersion: v1
data:
  password: {{ .Values.apps.password }}
  username: {{ .Values.apps.username }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    git: {{ .Values.apps.path }}
  name: argocd-repo
type: Opaque
