apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aop-shd-exithandler-kv
spec:
  provider: azure
  secretObjects:
    - secretName: aop-shd-exithandler-kv
      data:
        - key: aop-wfe-sb-order-automation-completed-topic
          objectName: aop-wfe-sb-order-automation-completed-topic
        - key: aop-wfe-sb-fqdn
          objectName: aop-wfe-sb-fqdn
        - key: aop-app-insights-instrumentation-key
          objectName: aop-app-insights-instrumentation-key
        - key: aop-wfe-sb-complete-connection-string
          objectName: aop-wfe-sb-complete-connection-string
      type: Opaque
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{.Values.managed_identity_id}}
    keyvaultName: {{.Values.kv_name}}
    objects: |
      array:
        - | 
          objectName: aop-wfe-sb-complete-connection-string
          objectType: secret
        - |   
          objectName: aop-wfe-sb-order-automation-completed-topic                                                                                     
          objectType: secret  
        - |   
          objectName: aop-wfe-sb-fqdn
          objectType: secret
        - |   
          objectName: aop-app-insights-instrumentation-key
          objectType: secret
    tenantId: {{.Values.tenant_id}}
